# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fm_UXtQJn74VAmXIGEZBFlsziJcp0iB
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_style("whitegrid")

df = pd.read_csv("/content/ecommerce_customer_data_custom_ratios.csv")

df.head()

df.info()
df.describe()

df.isnull().sum()

df.drop_duplicates(inplace=True)

df['Purchase Date'] = pd.to_datetime(df['Purchase Date'])

df['Month'] = df['Purchase Date'].dt.month
df['Year'] = df['Purchase Date'].dt.year

customer_spend = df.groupby('Customer ID')['Total Purchase Amount'].sum()

purchase_freq = df.groupby('Customer ID')['Purchase Date'].count()

snapshot_date = df['Purchase Date'].max()

rfm = df.groupby('Customer ID').agg({
    'Purchase Date': lambda x: (snapshot_date - x.max()).days,
    'Customer ID': 'count',
    'Total Purchase Amount': 'sum'
})

rfm.columns = ['Recency', 'Frequency', 'Monetary']
rfm.head()

rfm['Segment'] = pd.qcut(rfm['Monetary'], 4,
                         labels=['Low Value','Medium Value','High Value','VIP'])

rfm['Segment'].value_counts()

rfm['Segment'].value_counts().plot(kind='bar')
plt.title("Customer Segments")
plt.show()

df['Product Category'].value_counts().plot(kind='pie', autopct='%1.1f%%')
plt.title("Product Category Distribution")
plt.show()

df['Customer Age'].plot(kind='hist')
plt.title("Customer Age Distribution")
plt.show()

df['Churn'].value_counts()

sns.countplot(x='Churn', data=df)
plt.title("Customer Churn Distribution")
plt.show()

monthly_sales = df.groupby('Month')['Total Purchase Amount'].sum()

plt.figure(figsize=(8,5))
monthly_sales.plot(marker='o')
plt.title("Monthly Sales Trend")
plt.xlabel("Month")
plt.ylabel("Revenue")
plt.grid(True)
plt.show()

df['Returns'] = df['Returns'].fillna(0)

top_products = df.groupby('Product Category')['Total Purchase Amount'].sum().sort_values(ascending=False)

top_products.plot(kind='bar')
plt.title("Top Revenue Product Categories")
plt.show()

plt.figure(figsize=(8,5))
sns.histplot(df['Customer Age'], bins=20)
plt.title("Customer Age Distribution (Detailed)")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

"""## Key Insights

1. VIP customers generate the highest revenue compared to other customer segments.

2. Some product categories dominate customer purchases, showing strong customer preference.

3. Customers aged 25-40 appear to be the most active buyers.

4. Sales vary across different months, indicating seasonal purchasing behavior.

5. A noticeable number of customers have churned, meaning they stopped purchasing from the platform.

print('''
Key Insights

1. VIP customers generate the highest revenue compared to other customer segments.

2. Some product categories dominate customer purchases.

3. Customers aged 25-40 appear to be the most active buyers.

4. Sales vary across different months.

5. Some customers have churned.
''')
"""

print("""
Key Insights

1. VIP customers generate the highest revenue compared to other customer segments.

2. Some product categories dominate customer purchases, showing strong customer preference.

3. Customers aged 25-40 appear to be the most active buyers.

4. Sales vary across different months, indicating seasonal purchasing behavior.

5. A noticeable number of customers have churned, meaning they stopped purchasing from the platform.
""")

print("""
Actionable Recommendations for Alfido Tech

1. Introduce loyalty programs and rewards for VIP customers.

2. Focus marketing campaigns on customers aged 25-40.

3. Increase promotions for high-demand product categories.

4. Provide discounts and offers to inactive customers to reduce churn.

5. Launch seasonal marketing campaigns during low-sales months.
""")

print("""
Key Insights

1. VIP customers generate the highest revenue compared to other customer segments.

2. Some product categories dominate customer purchases.

3. Customers aged 25-40 appear to be the most active buyers.

4. Sales vary across different months.

5. Some customers have churned.
""")